# @package model
_target_: models.MARSE_Model
input_dim: 1024
dim: 384
max_seq_len: 50
num_steps: 10
decoding_policy: random

conformer_cfg:
  dim: ${model.dim}
  layers: 16
  dim_head: 32
  heads: 12
  conv_kernel_size: 10
  attn_dropout: 0.0
  ff_dropout: 0.0
  ff_mult: 4

dac_cfg:
  dac_model_type: "16khz"
  n_quantizers: 12
  sample_rate: 16000
