project:
  type: manuscript
  resources: 
    - "*.mp3"
    - "*.wav"
    - "resources/**/*.wav"

manuscript:
  article: index.qmd

format:
  html: default
  # docx: default
  # jats: default
  # pdf: default

execute:
  freeze: true



